/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\\public\\Solar_System.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Solar_System.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SUN.geometry} material={materials.SUN} position={[0, 0, 149]} scale={0.7} />
      <mesh geometry={nodes.MERCURY.geometry} material={materials.MERCURY} position={[0, 0, 92]} scale={0.002} />
      <mesh geometry={nodes.VENUS.geometry} material={nodes.VENUS.material} position={[0, 0, 41]} scale={0.006} />
      <mesh geometry={nodes.EARTH.geometry} material={materials.EARTH} scale={0.006} />
      <mesh geometry={nodes.MARS.geometry} material={nodes.MARS.material} position={[0, 0, -79]} scale={0.003} />
      <mesh geometry={nodes.JUPITER.geometry} material={nodes.JUPITER.material} position={[0, 0, -631]} scale={0.07} />
      <mesh geometry={nodes.SATURN.geometry} material={nodes.SATURN.material} position={[0, 0, -1288]} scale={0.003} />
      <mesh geometry={nodes.URANUS.geometry} material={nodes.URANUS.material} position={[0, 0, -2722]} />
      <mesh geometry={nodes.NEPTUNE.geometry} material={nodes.NEPTUNE.material} position={[0, 0, -4381]} scale={0.025} />
      <mesh geometry={nodes.MOON.geometry} material={materials.Moon} position={[0.379, 0, 0]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/Solar_System.glb')
