/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\3D\ISS.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ISS(props) {
  const { nodes, materials } = useGLTF('3D/ISS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurfa1_1.geometry} material={materials.blinn5SG} />
      <mesh geometry={nodes.polySurfa1_2.geometry} material={materials.blinn3SG} />
      <mesh geometry={nodes.polySurfa1_3.geometry} material={materials.blinn1SG} />
      <mesh geometry={nodes.polySurfa1_4.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.polySurfa1_5.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.polySurfa1_6.geometry} material={materials.blinn4SG} />
      <mesh geometry={nodes.polySurfa1_7.geometry} material={materials.soyuz_blinn2SG} />
      <mesh geometry={nodes.polySurfa1_8.geometry} material={materials.blinn7SG} />
      <mesh geometry={nodes.polySurfa1_9.geometry} material={materials.soyuz_blinn3SG} />
      <mesh geometry={nodes.polySurfa1_10.geometry} material={materials.blinn6SG} />
      <mesh geometry={nodes.polySurfa1_11.geometry} material={materials.bendedtruss_blin} />
      <mesh geometry={nodes.polySurfa1_12.geometry} material={materials.lambert6SG} />
      <mesh geometry={nodes.polySurfa1_13.geometry} material={materials.lambert2SG} />
      <mesh geometry={nodes.polySurfa1_14.geometry} material={materials.initialShadingGr} />
      <mesh geometry={nodes.polySurfa1_15.geometry} material={materials.anisotropic1SG} />
      <mesh geometry={nodes.polySurfa1_16.geometry} material={materials.apollohorns_blin} />
      <mesh geometry={nodes.polySurfa2_1.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.polySurfa2_2.geometry} material={materials.blinn3SG} />
      <mesh geometry={nodes.polySurfa2_3.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.polySurfa2_4.geometry} material={materials.anisotropic1SG} />
      <mesh geometry={nodes.polySurfa2_5.geometry} material={materials.apollohorns_blin} />
      <mesh geometry={nodes.polySurfa2_6.geometry} material={materials.blinn1SG} />
      <mesh geometry={nodes.polySurfa2_7.geometry} material={materials.lambert6SG} />
      <mesh geometry={nodes.polySurfa2_8.geometry} material={materials.initialShadingGr} />
      <mesh geometry={nodes.polySurfa2_9.geometry} material={materials.lambert7SG} />
      <mesh geometry={nodes.polySurfa2_10.geometry} material={materials.soyuz_blinn4SG} />
      <mesh geometry={nodes.polySurfa2_11.geometry} material={materials.soyuz_blinn3SG} />
      <mesh geometry={nodes.polySurfa3_1.geometry} material={materials.anisotropic1SG} />
      <mesh geometry={nodes.polySurfa3_2.geometry} material={materials.apollohorns_blin} />
    </group>
  )
}

useGLTF.preload('/ISS.glb')
