/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\\public\\Solar_System.glb 
*/

import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import {LayerMaterial, Depth, Fresnel, Noise} from 'lamina'

export function Solar_System_Broken(props) {
  const { nodes, materials } = useGLTF('/Solar_System.glb')
  return (
    <group  scale={0.001} {...props} dispose={null}>
      <mesh geometry={nodes.SUN.geometry} material={materials.SUN} position={[0, 0, 149]} scale={0.7} >
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                The sun
            </div>
        </Html>

      </mesh>
      <mesh geometry={nodes.MERCURY.geometry} material={materials.MERCURY} position={[0, 0, 92]} scale={0.002}>
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Mercury
            </div>
        </Html>

    </mesh>
      <mesh geometry={nodes.VENUS.geometry} material={nodes.VENUS.material} position={[0, 0, 41]} scale={0.006}>
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Venus
            </div>
        </Html>

    </mesh>
      <mesh geometry={nodes.EARTH.geometry} scale={0.006} material={nodes.EARTH.material}>
        <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Earth
            </div>
        </Html>
    </mesh>
      <mesh geometry={nodes.MARS.geometry} material={nodes.MARS.material} position={[0, 0, -79]} scale={0.003}>
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Mars
            </div>
        </Html>

      </mesh>
      <mesh geometry={nodes.JUPITER.geometry} material={nodes.JUPITER.material} position={[0, 0, -631]} scale={0.07}>
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Jupiter
            </div>
        </Html>

      </mesh>
      <mesh geometry={nodes.SATURN.geometry} material={nodes.SATURN.material} position={[0, 0, -1288]} scale={0.003} >
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Saturn
            </div>
        </Html>

      </mesh>
      <mesh geometry={nodes.URANUS.geometry} material={nodes.URANUS.material} position={[0, 0, -2722]} >
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Uranus
            </div>
        </Html>

      </mesh>
      <mesh geometry={nodes.NEPTUNE.geometry} material={nodes.NEPTUNE.material} position={[0, 0, -4381]} scale={0.025}>
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Neptune
            </div>
        </Html>

      </mesh>
      <mesh geometry={nodes.MOON.geometry} material={materials.Moon} position={[0.379, 0, 0]} scale={0.002}>
      <Html
        position={[0, -1.1, 0]}
        >
            <div className='planet_text'>
                Moon
            </div>
        </Html>

      </mesh>
    </group>
  )
}

useGLTF.preload('/Solar_System.glb')
